# XXX: tox does not support generative environment lists in TOML

requires = ["tox ~=4.27"]
env_list = ["3.13", "3.12", "3.11", "3.10"]

# XXX: This is... interesting.
[env_run_base]
description = "run unit tests (accumulating coverage data)"
extras = ["test"]
commands = [
    [
        "coverage", "run", "-p",
        "-m", "pytest",
        "{tty:--color=yes}",
        { replace = "posargs", default = ["tests"], extend = true },
    ],
]

[env.lint]
description = "run linters"
extras = ["dev"]
ignore_errors = true
commands = [
    [
        "flake8",
        "--extend-ignore=PT",   # "PT" is for codes from flake8-pytest-style
        { replace = "posargs", default = ["ordered_set"], extend = true},
    ],
    [
        "flake8",
        { replace = "posargs", default = ["conftest.py", "tests"], extend = true},
    ],
]
